"""Level 4 — Codegen golden tests (AGK-Real v1 test plan).

Each test asserts the EXACT Python output. Every output is also verified
with ast.parse (generated code must always be syntactically valid Python).
"""

import ast as py_ast

import pytest

from agk.parser import parse
from agk.semantic import analyze
from agk.codegen import generate


def gen(src):
    """Full pipeline: parse -> analyze -> generate. Validates the output
    parses as Python, then returns it."""
    prog = parse(src, filename="test.agk")
    prog, _warnings = analyze(prog, filename="test.agk")
    out = generate(prog)
    py_ast.parse(out)  # must always be valid Python
    return out


HEADER = "# Generated by AGK-Real v2 - do not edit\n"


# -- functions --------------------------------------------------------------------

def test_simple_function():
    assert gen("define function f:\n    return 1\n") == (
        HEADER + "def f():\n    return 1\n")


def test_function_params_and_return():
    out = gen(
        "define function add that takes a as Integer, b as Integer "
        "and returns Integer:\n"
        "    return a + b\n")
    assert out == (
        HEADER + "def add(a, b):\n    return a + b\n")


def test_create_emits_nothing_until_set():
    out = gen(
        "define function f:\n"
        "    create x as Integer\n"
        "    set x to 1\n"
        "    return x\n")
    assert out == (
        HEADER + "def f():\n    x = 1\n    return x\n")


def test_main_gets_entrypoint():
    out = gen("define function main:\n    print(\"hi\")\n")
    assert out == (
        HEADER + "def main():\n    print(\"hi\")\n"
        "\nif __name__ == \"__main__\":\n    main()\n")


def test_no_entrypoint_without_main():
    out = gen("define function f:\n    return 1\n")
    assert "__main__" not in out


def test_bare_return():
    out = gen("define function f:\n    return\n")
    assert out == HEADER + "def f():\n    return\n"


def test_multiple_top_level_separated():
    out = gen("import math\ndefine function f:\n    return 1\n")
    assert out == (
        HEADER + "import math\n\ndef f():\n    return 1\n")


# -- constants / imports ---------------------------------------------------------------

def test_constants():
    out = gen("define constant MAX as Integer = 100\n"
              'define constant NAME as String = "agk"\n')
    assert out == HEADER + 'MAX = 100\n\nNAME = "agk"\n'


def test_import():
    assert gen("import math\n") == HEADER + "import math\n"
    assert gen("import os.path\n") == HEADER + "import os.path\n"


# -- control flow -----------------------------------------------------------------------------

def test_if_elif_else():
    out = gen(
        "define function f that takes x as Integer:\n"
        "    if x > 5:\n"
        "        return 1\n"
        "    elif x > 2:\n"
        "        return 2\n"
        "    else:\n"
        "        return 3\n")
    assert out == (
        HEADER +
        "def f(x):\n"
        "    if x > 5:\n"
        "        return 1\n"
        "    elif x > 2:\n"
        "        return 2\n"
        "    else:\n"
        "        return 3\n")


def test_while():
    out = gen(
        "define function f:\n"
        "    create i as Integer\n"
        "    set i to 3\n"
        "    while i > 0:\n"
        "        set i to i - 1\n"
        "    return i\n")
    assert out == (
        HEADER +
        "def f():\n"
        "    i = 3\n"
        "    while i > 0:\n"
        "        i = i - 1\n"
        "    return i\n")


def test_for_each():
    out = gen(
        "define function f that takes items as List:\n"
        "    for each item in items:\n"
        "        print(item)\n")
    assert out == (
        HEADER +
        "def f(items):\n"
        "    for item in items:\n"
        "        print(item)\n")


def test_nested_blocks_indent():
    out = gen(
        "define function f:\n"
        "    create a as Boolean\n"
        "    set a to true\n"
        "    while a:\n"
        "        if a:\n"
        "            return 1\n"
        "    return 0\n")
    assert out == (
        HEADER +
        "def f():\n"
        "    a = True\n"
        "    while a:\n"
        "        if a:\n"
        "            return 1\n"
        "    return 0\n")


# -- expression precedence (parenthesization) -------------------------------------------------------

def test_precedence_no_parens_needed():
    out = gen("define function f:\n"
              "    create x as Integer\n"
              "    set x to 1 + 2 * 3\n"
              "    return x\n")
    assert "    x = 1 + 2 * 3\n" in out


def test_precedence_parens_added():
    out = gen("define function f:\n"
              "    create x as Integer\n"
              "    set x to (1 + 2) * 3\n"
              "    return x\n")
    assert "    x = (1 + 2) * 3\n" in out


def test_precedence_right_assoc_parens():
    out = gen(
        "define function f that takes a as Integer, b as Integer, c as Integer:\n"
        "    create x as Integer\n"
        "    set x to a - (b - c)\n"
        "    return x\n")
    assert "    x = a - (b - c)\n" in out


def test_precedence_left_assoc_no_parens():
    out = gen(
        "define function f that takes a as Integer, b as Integer, c as Integer:\n"
        "    create x as Integer\n"
        "    set x to a - b - c\n"
        "    return x\n")
    assert "    x = a - b - c\n" in out


def test_precedence_unary():
    out = gen(
        "define function f that takes a as Integer, b as Integer:\n"
        "    create x as Integer\n"
        "    set x to -(a + b)\n"
        "    return x\n")
    assert "    x = -(a + b)\n" in out


def test_precedence_boolean():
    out = gen(
        "define function f that takes a as Boolean, b as Boolean, c as Boolean:\n"
        "    create x as Boolean\n"
        "    set x to a or b and not c\n"
        "    return x\n")
    assert "    x = a or b and not c\n" in out


def test_precedence_comparison_chain():
    out = gen(
        "define function f that takes a as Integer, b as Integer, c as Integer:\n"
        "    create x as Boolean\n"
        "    set x to a < b == c\n"
        "    return x\n")
    assert "    x = a < b == c\n" in out


# -- literals / operators ----------------------------------------------------------------------------

def test_literals():
    out = gen(
        "define function f:\n"
        "    create a as Integer\n"
        "    create b as Float\n"
        '    create c as String\n'
        "    create d as Boolean\n"
        "    set a to 42\n"
        "    set b to 2.5\n"
        '    set c to "hi"\n'
        "    set d to false\n"
        "    return a\n")
    assert "\n".join([
        "    a = 42", "    b = 2.5", '    c = "hi"', "    d = False",
    ]) + "\n" in out


def test_string_escapes_roundtrip():
    out = gen(
        "define function f:\n"
        "    create x as String\n"
        '    set x to "a\\"b"\n'
        "    return x\n")
    assert '    x = "a\\"b"\n' in out


def test_operators_all():
    out = gen(
        "define function f that takes a as Integer, b as Integer:\n"
        "    create r as Integer\n"
        "    set r to a % b\n"
        "    return r\n")
    assert "    r = a % b\n" in out


def test_list_dict_index():
    out = gen(
        "define function f:\n"
        "    create xs as List\n"
        "    set xs to [1, 2, 3]\n"
        '    create d as Object\n'
        '    set d to {"a": 1}\n'
        "    return xs[0]\n")
    assert "    xs = [1, 2, 3]\n" in out
    assert '    d = {"a": 1}\n' in out
    assert "    return xs[0]\n" in out


def test_call_attribute_chained():
    out = gen(
        "define function f that takes d as Object:\n"
        "    return d.keys()[0]\n")
    assert "    return d.keys()[0]\n" in out


# -- classes -----------------------------------------------------------------------------

def test_class_fields_constructor_method():
    out = gen(
        "define class Person:\n"
        "    variable name as String\n"
        "    define constructor that takes n as String:\n"
        "        set name to n\n"
        "    define function greet that returns String:\n"
        "        return name\n")
    assert out == (
        HEADER +
        "class Person:\n"
        "    def __init__(self, n):\n"
        "        self.name = n\n"
        "    def greet(self):\n"
        "        return self.name\n")


def test_class_extends():
    out = gen(
        "define class Animal:\n"
        "    variable legs as Integer\n"
        "define class Dog extends Animal:\n"
        "    variable name as String\n")
    assert out == (
        HEADER +
        "class Animal:\n"
        "    def __init__(self):\n"
        "        self.legs = None\n"
        "\n"
        "class Dog(Animal):\n"
        "    def __init__(self):\n"
        "        self.name = None\n")


def test_class_method_call_and_instantiation():
    out = gen(
        "define class Counter:\n"
        "    variable n as Integer\n"
        "    define constructor:\n"
        "        set n to 0\n"
        "    define function bump:\n"
        "        set n to n + 1\n"
        "define function main:\n"
        "    create c as Object\n"
        "    set c to Counter()\n"
        "    c.bump()\n")
    assert "class Counter:\n" in out
    assert "    def __init__(self):\n        self.n = 0\n" in out
    assert "    def bump(self):\n        self.n = self.n + 1\n" in out
    assert "    c = Counter()\n    c.bump()\n" in out
    assert out.rstrip().endswith("main()")


def test_explicit_self_preserved():
    out = gen(
        "define class C:\n"
        "    variable x as Integer\n"
        "    define function get that returns Integer:\n"
        "        return self.x\n")
    assert "        return self.x\n" in out
