"""AGK-Real v2 Python code generator.

Translates the semantically-analyzed AST to plain Python 3 (no runtime
dependency). Expression emission is precedence-aware: parentheses are
added exactly when the child binds less tightly than its context.
"""

from . import ast_nodes as A
from .ffi import FFI_CTYPES

_PREC = {
    "or": 1,
    "and": 2,
    "==": 3, "!=": 3,
    "<": 4, ">": 4, "<=": 4, ">=": 4,
    "+": 5, "-": 5,
    "*": 6, "/": 6, "%": 6,
}
_UNARY_PREC = 7
_AWAIT_PREC = 8  # v0.4.0: `await` binds tighter than unary `-`/`not`
_ATOM_PREC = 9


def _quote(s):
    return '"' + (s.replace("\\", "\\\\").replace('"', '\\"')
                   .replace("\n", "\\n").replace("\t", "\\t")) + '"'


def _is_format_call(node):
    """True for `"…".format(…)` — which is how interpolated string
    literals desugar, so the result is statically known to be a str."""
    return (isinstance(node, A.Call)
            and isinstance(node.func, A.Attribute)
            and node.func.attr == "format"
            and isinstance(node.func.obj, A.StringLit))


class CodeGenerator:
    def __init__(self, agk_file=None):
        self.lines = []
        self.indent = 0
        self._started = False  # blank-line separator state across programs
        # FFI state: loader emitted once, one ctypes.CDLL handle per
        # distinct `from "<lib>"` string.
        self._extern_loader_emitted = False
        self._extern_libs = {}
        # When agk_file is set, every emitted statement line gets a
        # trailing `# AGK <file>:<line>` comment so tracebacks can be
        # mapped back to AGK source lines (see pipeline.rewrite_traceback).
        self._agk_file = agk_file

    def emit(self, text, node=None):
        line = "    " * self.indent + text
        if (self._agk_file and node is not None and text.strip()
                and getattr(node, "line", 0)):
            line += f"  # AGK {self._agk_file}:{node.line}"
        self.lines.append(line)

    # -- entry ------------------------------------------------------------

    def generate_program(self, program, skip_imports=frozenset(),
                         agk_file=None):
        """Emit one program's top-level statements, skipping resolved
        (inlined) module imports."""
        if agk_file is not None:
            self._agk_file = agk_file
        for stmt in program.statements:
            if isinstance(stmt, A.Import) and stmt.module in skip_imports:
                continue
            if self._started:
                self.emit("")
            self._started = True
            self.gen_top(stmt)

    def generate(self, program):
        self.emit("# Generated by AGK-Real v2 - do not edit")
        if program_uses_async(program) and not _asyncio_imported([program]):
            self.emit("import asyncio")
        self.generate_program(program)
        main_def = next((s for s in program.statements
                         if isinstance(s, A.FunctionDef) and s.name == "main"),
                        None)
        if main_def is not None:
            self.emit("")
            self.emit('if __name__ == "__main__":')
            self.indent += 1
            # v0.4.0: an async main runs on the event loop.
            if main_def.is_async:
                self.emit("asyncio.run(main())", main_def)
            else:
                self.emit("main()")
            self.indent -= 1
        return "\n".join(self.lines) + "\n"

    def gen_top(self, stmt):
        if isinstance(stmt, A.Import):
            self.emit(f"import {stmt.module}", stmt)
        elif isinstance(stmt, A.ConstantDef):
            self.emit(f"{stmt.name} = {self.expr(stmt.value)}", stmt)
        elif isinstance(stmt, A.FunctionDef):
            self.gen_def(stmt.name, stmt.params, stmt.body, node=stmt)
        elif isinstance(stmt, A.ExternDef):
            self.gen_extern(stmt)
        elif isinstance(stmt, A.ClassDef):
            self.gen_class(stmt)
        else:  # pragma: no cover - parser/semantic never produce this
            raise AssertionError(f"unexpected top-level node: {stmt!r}")

    def gen_def(self, name, params, body, extra_params=(), node=None):
        names = list(extra_params) + [
            p.name if p.default is None
            else f"{p.name}={self.expr(p.default)}"
            for p in params
        ]
        decorators = getattr(node, "decorators", None) or []
        for d in decorators:
            self.emit("@" + self.expr(d), node)
        async_kw = "async " if getattr(node, "is_async", False) else ""
        self.emit(f"{async_kw}def {name}({', '.join(names)}):", node)
        self.indent += 1
        for s in body:
            self.gen_stmt(s)
        self.indent -= 1

    def gen_extern(self, ext):
        """Emit a ctypes-based wrapper for an `extern function`.

        Each distinct library is loaded once via _agk_load_library
        (a path is used as-is; otherwise ctypes.util.find_library
        resolves the name, falling back to the name itself). String
        arguments are utf-8 encoded; String results are decoded, with
        a NULL guard mapping to None.
        """
        lib_var = self._extern_lib_var(ext.lib, ext)
        fn_var = f"_agk_extern_{ext.name}"
        self.emit(f"{fn_var} = {lib_var}.{ext.name}", ext)
        argtypes = ", ".join(FFI_CTYPES[p.type_name] for p in ext.params)
        self.emit(f"{fn_var}.argtypes = [{argtypes}]", ext)
        restype = FFI_CTYPES[ext.return_type] if ext.return_type else "None"
        self.emit(f"{fn_var}.restype = {restype}", ext)
        params = ", ".join(p.name for p in ext.params)
        self.emit(f"def {ext.name}({params}):", ext)
        self.indent += 1
        args = ", ".join(self._extern_arg(p) for p in ext.params)
        call = f"{fn_var}({args})"
        if ext.return_type == "String":
            self.emit("_r = " + call, ext)
            self.emit('_r = None if _r is None else _r.decode("utf-8")',
                       ext)
            self.emit("return _r", ext)
        else:
            self.emit(f"return {call}", ext)
        self.indent -= 1

    def _extern_arg(self, param):
        if param.type_name == "String":
            return f'{param.name}.encode("utf-8")'
        return param.name

    def _extern_lib_var(self, lib, node):
        """Return the variable holding the loaded library, emitting the
        loader helper and the CDLL call on first use."""
        if lib in self._extern_libs:
            return self._extern_libs[lib]
        if not self._extern_loader_emitted:
            self.emit("import ctypes", node)
            self.emit("import ctypes.util", node)
            self.emit("def _agk_load_library(name):", node)
            self.indent += 1
            self.emit('if "/" in name or name.startswith("."):', node)
            self.indent += 1
            self.emit("path = name", node)
            self.indent -= 1
            self.emit("else:", node)
            self.indent += 1
            self.emit("path = ctypes.util.find_library(name) or name",
                       node)
            self.indent -= 1
            self.emit("return ctypes.CDLL(path)", node)
            self.indent -= 1
            self._extern_loader_emitted = True
        var = f"_agk_lib{len(self._extern_libs)}"
        self.emit(f"{var} = _agk_load_library({_quote(lib)})", node)
        self._extern_libs[lib] = var
        return var

    def gen_class(self, cls):
        base = f"({cls.base})" if cls.base else ""
        self.emit(f"class {cls.name}{base}:", cls)
        self.indent += 1
        if cls.constructor:
            self.gen_def("__init__", cls.constructor.params,
                         cls.constructor.body, extra_params=("self",),
                         node=cls.constructor)
        elif cls.fields:
            self.emit("def __init__(self):")
            self.indent += 1
            for f in cls.fields:
                self.emit(f"self.{f.name} = None")
            self.indent -= 1
        for m in cls.methods:
            self.gen_def(m.name, m.params, m.body, extra_params=("self",),
                         node=m)
        self.indent -= 1

    # -- statements ---------------------------------------------------------

    def gen_stmt(self, s):
        if isinstance(s, A.CreateStmt):
            pass  # declaration only; no output until `set`
        elif isinstance(s, A.SetStmt):
            self.emit(f"{s.name} = {self.expr(s.value)}", s)
        elif isinstance(s, A.SetAttr):
            self.emit(f"{self.expr(s.obj)}.{s.attr} = {self.expr(s.value)}", s)
        elif isinstance(s, A.IfStmt):
            self.emit(f"if {self.expr(s.condition)}:", s)
            self.gen_block(s.then_body)
            for cond, body in s.elifs:
                self.emit(f"elif {self.expr(cond)}:")
                self.gen_block(body)
            if s.else_body is not None:
                self.emit("else:")
                self.gen_block(s.else_body)
        elif isinstance(s, A.WhileStmt):
            self.emit(f"while {self.expr(s.condition)}:", s)
            self.gen_block(s.body)
        elif isinstance(s, A.ForEachStmt):
            self.emit(f"for {s.var} in {self.expr(s.iterable)}:", s)
            self.gen_block(s.body)
        elif isinstance(s, A.ForRangeStmt):
            start, end = self.expr(s.start), self.expr(s.end)
            if s.step is None:
                self.emit(f"for {s.var} in range({start}, ({end}) + 1):", s)
            else:
                step = self.expr(s.step)
                # inclusive on both ends, counting up or down
                stop = (f"(({end}) + 1) if (({step}) > 0) "
                        f"else (({end}) - 1)")
                self.emit(f"for {s.var} in range({start}, {stop}, {step}):",
                          s)
            self.gen_block(s.body)
        elif isinstance(s, A.TryStmt):
            self.emit("try:", s)
            self.gen_block(s.body)
            if s.catch_body is not None:
                if s.catch_name:
                    self.emit(f"except Exception as {s.catch_name}:", s)
                else:
                    self.emit("except Exception:", s)
                self.gen_block(s.catch_body)
            if s.finally_body is not None:
                self.emit("finally:", s)
                self.gen_block(s.finally_body)
        elif isinstance(s, A.RaiseStmt):
            if s.value is None:
                self.emit("raise", s)
            elif isinstance(s.value, A.StringLit) or _is_format_call(s.value):
                # v2: `raise "message"` raises Exception("message") so a
                # plain string message just works (Python forbids raising
                # a bare str). Interpolated strings desugar to
                # "…".format(…) — still a str, so they get the same wrap.
                self.emit(f"raise Exception({self.expr(s.value)})", s)
            else:
                self.emit(f"raise {self.expr(s.value)}", s)
        elif isinstance(s, A.ReturnStmt):
            if s.value is None:
                self.emit("return", s)
            else:
                self.emit(f"return {self.expr(s.value)}", s)
        elif isinstance(s, A.YieldStmt):
            # v0.4.0: presence of `yield` makes this a generator function.
            if s.value is None:
                self.emit("yield", s)
            else:
                self.emit(f"yield {self.expr(s.value)}", s)
        elif isinstance(s, A.ExprStmt):
            self.emit(self.expr(s.expr), s)
        else:  # pragma: no cover
            raise AssertionError(f"unexpected statement: {s!r}")

    def gen_block(self, stmts):
        self.indent += 1
        for s in stmts:
            self.gen_stmt(s)
        self.indent -= 1

    # -- expressions ----------------------------------------------------------

    def expr(self, node, parent_prec=0):
        if isinstance(node, A.IntLit):
            return str(node.value)
        if isinstance(node, A.FloatLit):
            return repr(node.value)
        if isinstance(node, A.StringLit):
            return _quote(node.value)
        if isinstance(node, A.BoolLit):
            return "True" if node.value else "False"
        if isinstance(node, A.Name):
            return node.id
        if isinstance(node, A.BinOp):
            prec = _PREC[node.op]
            left = self.expr(node.left, prec)
            right = self.expr(node.right, prec + 1)
            text = f"{left} {node.op} {right}"
            return f"({text})" if prec < parent_prec else text
        if isinstance(node, A.UnaryOp):
            operand = self.expr(node.operand, _UNARY_PREC)
            text = f"-{operand}" if node.op == "-" else f"not {operand}"
            return f"({text})" if _UNARY_PREC < parent_prec else text
        if isinstance(node, A.AwaitExpr):
            # v0.4.0: `await` binds tighter than unary minus, so
            # `await -x` is `await (-x)`; `-await x` stays unparenthesised.
            operand = self.expr(node.operand, _ATOM_PREC)
            text = f"await {operand}"
            return f"({text})" if _AWAIT_PREC < parent_prec else text
        if isinstance(node, A.Call):
            args = ", ".join(self.expr(a) for a in node.args)
            return f"{self.expr(node.func, _ATOM_PREC)}({args})"
        if isinstance(node, A.Attribute):
            return f"{self.expr(node.obj, _ATOM_PREC)}.{node.attr}"
        if isinstance(node, A.Index):
            return f"{self.expr(node.obj, _ATOM_PREC)}[{self.expr(node.index)}]"
        if isinstance(node, A.ListLit):
            return "[" + ", ".join(self.expr(e) for e in node.elements) + "]"
        if isinstance(node, A.DictLit):
            pairs = ", ".join(f"{self.expr(k)}: {self.expr(v)}"
                              for k, v in node.pairs)
            return "{" + pairs + "}"
        raise AssertionError(f"unexpected expression: {node!r}")  # pragma: no cover


def generate(program):
    """Generate Python source for a semantically-analyzed program."""
    return CodeGenerator().generate(program)


def program_uses_async(program):
    """True if any function or method in the program is `async`."""
    for stmt in program.statements:
        if isinstance(stmt, A.FunctionDef) and stmt.is_async:
            return True
        if isinstance(stmt, A.ClassDef):
            if any(m.is_async for m in stmt.methods):
                return True
    return False


def _asyncio_imported(programs):
    """True if any program already has a plain `import asyncio`."""
    return any(isinstance(s, A.Import) and s.module == "asyncio"
               for p in programs for s in p.statements)
