"""AGK-Real v2 pipeline: parse -> analyze -> generate -> (optionally) run.

Module imports: ``import <name>`` first looks for ``<name>.agk`` next to
the importing file, in the given search paths, then in the bundled
stdlib. A found module is compiled and inlined (its functions, classes
and constants become directly callable); anything else falls through to
a plain Python ``import <name>``.
"""

import io
import os
import re
import traceback
from contextlib import redirect_stdout
from pathlib import Path

from . import ast_nodes as A
from .parser import parse
from .semantic import analyze
from .codegen import CodeGenerator

STDLIB_DIR = Path(__file__).parent / "stdlib"
HEADER = "# Generated by AGK-Real v2 - do not edit"


def _find_module(name, base_dir, search_paths):
    """Locate <name>.agk. Returns a Path or None. Dotted names are
    always Python imports, never .agk modules."""
    if "." in name:
        return None
    dirs = []
    if base_dir:
        dirs.append(base_dir)
    dirs.extend(search_paths)
    dirs.append(STDLIB_DIR)
    for d in dirs:
        candidate = Path(d) / f"{name}.agk"
        if candidate.is_file():
            return candidate
    return None


def _resolve_modules(program, filename, search_paths, _seen=None):
    """Compile-time include resolution. Returns [(name, Program, path)]
    in dependency order. Cycles are tolerated (skipped on revisit)."""
    seen = _seen if _seen is not None else set()
    modules = []
    base_dir = None
    if filename not in (None, "<string>", "<input>", "<repl>"):
        parent = os.path.dirname(os.path.abspath(filename))
        if os.path.isdir(parent):
            base_dir = parent
    for stmt in program.statements:
        if not isinstance(stmt, A.Import) or stmt.module in seen:
            continue
        seen.add(stmt.module)
        path = _find_module(stmt.module, base_dir, search_paths)
        if path is None:
            continue  # plain Python import; emitted as-is
        mod_prog = parse(path.read_text(), filename=str(path))
        modules.extend(_resolve_modules(mod_prog, str(path), search_paths, seen))
        modules.append((stmt.module, mod_prog, str(path)))
    return modules


def _generate_all(program, modules, resolved, filename, annotate):
    cg = CodeGenerator()
    cg.emit(HEADER)
    for _name, mod_prog, mod_path in modules:
        cg.generate_program(mod_prog, skip_imports=resolved,
                            agk_file=mod_path if annotate else None)
    cg.generate_program(program, skip_imports=resolved,
                        agk_file=filename if annotate else None)
    main_def = next((s for s in program.statements
                     if isinstance(s, A.FunctionDef) and s.name == "main"),
                    None)
    if main_def is not None:
        cg.emit("")
        cg.emit('if __name__ == "__main__":')
        cg.indent += 1
        cg.emit("main()", main_def)
        cg.indent -= 1
    return "\n".join(cg.lines) + "\n"


_AGK_COMMENT = re.compile(r"# AGK (.+):(\d+)\s*$")


def _agk_line_map(code):
    """{generated python lineno: (agk_file, agk_lineno)} from the
    `# AGK file:line` comments (emitted when annotate=True)."""
    line_map = {}
    for i, line in enumerate(code.splitlines(), start=1):
        m = _AGK_COMMENT.search(line)
        if m:
            line_map[i] = (m.group(1), int(m.group(2)))
    return line_map


def format_agk_traceback(exc_type, exc_value, tb, code):
    """Format an exception like a Python traceback, but with AGK
    file:line for frames that came from AGK code.

    Requires code compiled with annotate=True. Mapped frames show
    `File "<agk file>", line <n>` plus that AGK source line; other
    frames (Python stdlib, unannotated lines) use the normal rendering.
    """
    line_map = _agk_line_map(code)
    file_cache = {}

    def agk_source(path, lineno):
        if path not in file_cache:
            try:
                with open(path, encoding="utf-8") as f:
                    file_cache[path] = f.read().splitlines()
            except OSError:
                file_cache[path] = []
        lines = file_cache[path]
        if 1 <= lineno <= len(lines):
            return lines[lineno - 1].strip()
        return ""

    out = ["Traceback (most recent call last):"]
    while tb is not None:
        code_obj = tb.tb_frame.f_code
        # The exec() call in `agk run` itself is noise: skip it so the
        # user only sees their own code (and any library frames).
        if not (code_obj.co_name == "cmd_run"
                and code_obj.co_filename.endswith("/agk/__main__.py")):
            lineno = tb.tb_lineno
            name = code_obj.co_name
            if lineno in line_map:
                agk_file, agk_lineno = line_map[lineno]
                out.append(f'  File "{agk_file}", line {agk_lineno}, in {name}')
                src = agk_source(agk_file, agk_lineno)
                if src:
                    out.append(f"    {src}")
            else:
                for item in traceback.format_list(
                        traceback.extract_tb(tb, limit=1)):
                    out.append(item.rstrip("\n"))
        tb = tb.tb_next
    out.append("".join(
        traceback.format_exception_only(exc_type, exc_value)).rstrip("\n"))
    return "\n".join(out) + "\n"


def compile_program(program, filename="<string>", search_paths=(),
                    extra_top_levels=(), annotate=False):
    """Compile an already-parsed program. Returns (code, warnings, modules).

    annotate=True appends `# AGK file:line` comments to generated lines
    so runtime tracebacks can be mapped back to AGK source lines.
    """
    if search_paths is None:
        search_paths = [os.getcwd()]
    modules = _resolve_modules(program, filename, list(search_paths))
    warnings = []
    for _name, mod_prog, mod_file in modules:
        _, mod_warnings = analyze(mod_prog, filename=mod_file)
        warnings.extend(mod_warnings)
    resolved = {name for name, _, _ in modules}
    extra = list(extra_top_levels) + [mp for _, mp, _ in modules]
    program, main_warnings = analyze(program, filename=filename,
                                     extra_top_levels=extra)
    warnings.extend(main_warnings)
    return (_generate_all(program, modules, resolved, filename, annotate),
            warnings, modules)


def compile_source(source, filename="<string>", search_paths=(),
                   extra_top_levels=(), annotate=False):
    """Compile AGK source to Python. Returns (python_code, warnings)."""
    program = parse(source, filename=filename)
    code, warnings, _ = compile_program(
        program, filename=filename, search_paths=search_paths,
        extra_top_levels=extra_top_levels, annotate=annotate)
    return code, warnings


def run_source(source, filename="<string>", search_paths=()):
    """Compile and execute AGK source. Returns (stdout, namespace, warnings).

    The program runs as __main__ so a `define function main:` entrypoint
    executes automatically.
    """
    code, warnings = compile_source(source, filename,
                                    search_paths=search_paths)
    namespace = {"__name__": "__main__"}
    buf = io.StringIO()
    with redirect_stdout(buf):
        exec(compile(code, filename, "exec"), namespace)
    return buf.getvalue(), namespace, warnings
