"""AGK-Real v2 pipeline: parse -> analyze -> generate -> (optionally) run.

Module imports: ``import <name>`` first looks for ``<name>.agk`` next to
the importing file, in the given search paths, then in the bundled
stdlib, then in installed packages (``packages/<dep>/`` from the
nearest agk.json). A found module is compiled and inlined (its
functions, classes and constants become directly callable); anything
else falls through to a plain Python ``import <name>``.
"""

import hashlib
import io
import json
import os
import re
import shutil
import traceback
from contextlib import redirect_stdout
from pathlib import Path

from . import ast_nodes as A
from .parser import parse
from .pkg import package_module_dirs
from .semantic import analyze
from .typecheck import typecheck
from .codegen import CodeGenerator, program_uses_async, _asyncio_imported
from .optimize import optimize_program

STDLIB_DIR = Path(__file__).parent / "stdlib"
HEADER = "# Generated by AGK-Real v2 - do not edit"


def _find_module(name, base_dir, search_paths, pkg_dirs=()):
    """Locate <name>.agk. Returns a Path or None. Dotted names are
    always Python imports, never .agk modules.

    Precedence: the importing file's directory, then the caller search
    paths, then the bundled stdlib, then installed packages
    (packages/<dep>/ from the project's agk.json).
    """
    if "." in name:
        return None
    dirs = []
    if base_dir:
        dirs.append(base_dir)
    dirs.extend(search_paths)
    dirs.append(STDLIB_DIR)
    dirs.extend(pkg_dirs)
    for d in dirs:
        candidate = Path(d) / f"{name}.agk"
        if candidate.is_file():
            return candidate
    return None


def _resolve_modules(program, filename, search_paths, _seen=None, pkg_dirs=()):
    """Compile-time include resolution. Returns [(name, Program, path)]
    in dependency order. Cycles are tolerated (skipped on revisit)."""
    seen = _seen if _seen is not None else set()
    modules = []
    base_dir = None
    if filename not in (None, "<string>", "<input>", "<repl>"):
        parent = os.path.dirname(os.path.abspath(filename))
        if os.path.isdir(parent):
            base_dir = parent
    for stmt in program.statements:
        if not isinstance(stmt, A.Import) or stmt.module in seen:
            continue
        seen.add(stmt.module)
        path = _find_module(stmt.module, base_dir, search_paths, pkg_dirs)
        if path is None:
            continue  # plain Python import; emitted as-is
        mod_prog = parse(path.read_text(), filename=str(path))
        modules.extend(_resolve_modules(mod_prog, str(path), search_paths,
                                        seen, pkg_dirs))
        modules.append((stmt.module, mod_prog, str(path)))
    return modules


def _generate_all(program, modules, resolved, filename, annotate):
    cg = CodeGenerator()
    cg.emit(HEADER)
    # v0.4.0: async functions need the event loop available.
    mod_progs = [mp for _, mp, _ in modules]
    if ((program_uses_async(program)
            or any(program_uses_async(mp) for mp in mod_progs))
            and not _asyncio_imported([program] + mod_progs)):
        cg.emit("import asyncio")
    for _name, mod_prog, mod_path in modules:
        cg.generate_program(mod_prog, skip_imports=resolved,
                            agk_file=mod_path if annotate else None)
    cg.generate_program(program, skip_imports=resolved,
                        agk_file=filename if annotate else None)
    main_def = next((s for s in program.statements
                     if isinstance(s, A.FunctionDef) and s.name == "main"),
                    None)
    if main_def is not None:
        cg.emit("")
        cg.emit('if __name__ == "__main__":')
        cg.indent += 1
        if main_def.is_async:
            cg.emit("asyncio.run(main())", main_def)
        else:
            cg.emit("main()", main_def)
        cg.indent -= 1
    return "\n".join(cg.lines) + "\n"


_AGK_COMMENT = re.compile(r"# AGK (.+):(\d+)\s*$")


def agk_line_map(code):
    """{generated python lineno: (agk_file, agk_lineno)} from the
    `# AGK file:line` comments (emitted when annotate=True). Public so
    tools like the debugger can map generated code back to AGK source."""
    line_map = {}
    for i, line in enumerate(code.splitlines(), start=1):
        m = _AGK_COMMENT.search(line)
        if m:
            line_map[i] = (m.group(1), int(m.group(2)))
    return line_map


def format_agk_traceback(exc_type, exc_value, tb, code):
    """Format an exception like a Python traceback, but with AGK
    file:line for frames that came from AGK code.

    Requires code compiled with annotate=True. Mapped frames show
    `File "<agk file>", line <n>` plus that AGK source line; other
    frames (Python stdlib, unannotated lines) use the normal rendering.
    """
    line_map = agk_line_map(code)
    file_cache = {}

    def agk_source(path, lineno):
        if path not in file_cache:
            try:
                with open(path, encoding="utf-8") as f:
                    file_cache[path] = f.read().splitlines()
            except OSError:
                file_cache[path] = []
        lines = file_cache[path]
        if 1 <= lineno <= len(lines):
            return lines[lineno - 1].strip()
        return ""

    out = ["Traceback (most recent call last):"]
    while tb is not None:
        code_obj = tb.tb_frame.f_code
        # The exec() call in `agk run` itself is noise: skip it so the
        # user only sees their own code (and any library frames).
        if not (code_obj.co_name == "cmd_run"
                and code_obj.co_filename.endswith("/agk/__main__.py")):
            lineno = tb.tb_lineno
            name = code_obj.co_name
            if lineno in line_map:
                agk_file, agk_lineno = line_map[lineno]
                out.append(f'  File "{agk_file}", line {agk_lineno}, in {name}')
                src = agk_source(agk_file, agk_lineno)
                if src:
                    out.append(f"    {src}")
            else:
                for item in traceback.format_list(
                        traceback.extract_tb(tb, limit=1)):
                    out.append(item.rstrip("\n"))
        tb = tb.tb_next
    out.append("".join(
        traceback.format_exception_only(exc_type, exc_value)).rstrip("\n"))
    return "\n".join(out) + "\n"


def compile_program(program, filename="<string>", search_paths=(),
                    extra_top_levels=(), annotate=False, optimize=True):
    """Compile an already-parsed program. Returns (code, warnings, modules).

    annotate=True appends `# AGK file:line` comments to generated lines
    so runtime tracebacks can be mapped back to AGK source lines.
    optimize=True (default) runs the AST optimization pass
    (agk.optimize) after semantic analysis, before codegen.
    """
    if search_paths is None:
        search_paths = [os.getcwd()]
    if filename not in (None, "<string>", "<input>", "<repl>"):
        entry_dir = os.path.dirname(os.path.abspath(filename))
    else:
        entry_dir = os.getcwd()
    pkg_dirs = package_module_dirs(entry_dir)
    modules = _resolve_modules(program, filename, list(search_paths),
                               pkg_dirs=pkg_dirs)
    warnings = []
    seen_progs = []
    for _name, mod_prog, mod_file in modules:
        _, mod_warnings = analyze(mod_prog, filename=mod_file,
                                  extra_top_levels=seen_progs)
        typecheck(mod_prog, filename=mod_file, extra_top_levels=seen_progs)
        if optimize:
            optimize_program(mod_prog)
        warnings.extend(mod_warnings)
        seen_progs.append(mod_prog)
    resolved = {name for name, _, _ in modules}
    extra = list(extra_top_levels) + [mp for _, mp, _ in modules]
    program, main_warnings = analyze(program, filename=filename,
                                     extra_top_levels=extra)
    typecheck(program, filename=filename, extra_top_levels=extra)
    if optimize:
        optimize_program(program)
    warnings.extend(main_warnings)
    return (_generate_all(program, modules, resolved, filename, annotate),
            warnings, modules)


def compile_source(source, filename="<string>", search_paths=(),
                   extra_top_levels=(), annotate=False, optimize=True):
    """Compile AGK source to Python. Returns (python_code, warnings)."""
    program = parse(source, filename=filename)
    code, warnings, _ = compile_program(
        program, filename=filename, search_paths=search_paths,
        extra_top_levels=extra_top_levels, annotate=annotate,
        optimize=optimize)
    return code, warnings


def run_source(source, filename="<string>", search_paths=(), optimize=True):
    """Compile and execute AGK source. Returns (stdout, namespace, warnings).

    The program runs as __main__ so a `define function main:` entrypoint
    executes automatically.
    """
    code, warnings = compile_source(source, filename,
                                    search_paths=search_paths,
                                    optimize=optimize)
    namespace = {"__name__": "__main__"}
    buf = io.StringIO()
    with redirect_stdout(buf):
        exec(compile(code, filename, "exec"), namespace)
    return buf.getvalue(), namespace, warnings


# ---------------------------------------------------------------------------
# Incremental compilation cache (used by `agk build`).
#
# `<entry-dir>/.agkcache/manifest.json` maps each compiled .agk file's
# absolute path to an entry:
#   {"fingerprint": <hex>, "chunk": <generated python>, "warnings": [...]}
# The entry file additionally stores the fully assembled output under "code".
#
# Fingerprint design (cache key): sha256 over
#     compiler version                      <- any compiler upgrade
#                                            invalidates the whole cache
#     \x00
#     sha256 of the module's own source bytes
#     \x00
#     the fingerprints of its direct .agk imports, sorted
# A module's fingerprint therefore incorporates its dependencies'
# fingerprints recursively, so editing a module transitively invalidates
# every importer: dependents are conservatively recompiled (we do not try
# to prove a dependent is unaffected by a dependency change). Plain Python
# imports (unresolved or dotted names) are not tracked -- they emit
# verbatim and cannot affect AGK codegen.
#
# Skipping analyze()/typecheck()/optimize()/codegen on a cache hit is
# sound because a hit implies the module's source AND every transitive
# dependency's source are byte identical to the cached build. analyze()
# and typecheck() only read top-level names/signatures (never mutate)
# from the extra_top_levels programs, so their outcomes are pinned by
# the fingerprint too.

CACHE_DIR_NAME = ".agkcache"
CACHE_FORMAT = 1
# Keep in sync with pyproject.toml. Any compiler change must invalidate
# previously cached codegen, so the version salts every fingerprint.
COMPILER_VERSION = "0.5.0"

_MANIFEST_NAME = "manifest.json"


def _source_hash_bytes(data):
    return hashlib.sha256(data).hexdigest()


def _fingerprint(src_hash, dep_fps, salt=""):
    h = hashlib.sha256()
    h.update(("agk-cache-v%d:%s\x00" % (CACHE_FORMAT, COMPILER_VERSION))
             .encode("utf-8"))
    h.update(salt.encode("utf-8"))
    h.update(b"\x00")
    h.update(src_hash.encode("utf-8"))
    for d in dep_fps:
        h.update(b"\x00")
        h.update(d.encode("utf-8"))
    return h.hexdigest()


def _direct_agk_deps(mod_prog, mod_path, search_paths, pkg_dirs=()):
    """Absolute paths of the .agk modules mod_prog directly imports.

    Mirrors _resolve_modules' lookup (including pkg_dirs) so the
    dependency graph covers every module that gets inlined.
    """
    base = os.path.dirname(os.path.abspath(mod_path))
    deps = []
    for stmt in mod_prog.statements:
        if isinstance(stmt, A.Import):
            found = _find_module(stmt.module, base, list(search_paths),
                                 pkg_dirs)
            if found is not None:
                deps.append(os.path.abspath(str(found)))
    return deps


def _load_manifest(cache_dir):
    """Read the cache manifest; {} when missing, corrupt, or written by a
    different compiler version (stale caches invalidate on upgrade)."""
    try:
        with open(os.path.join(cache_dir, _MANIFEST_NAME),
                  encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError):
        return {}
    if not isinstance(data, dict):
        return {}
    if (data.get("format") != CACHE_FORMAT
            or data.get("version") != COMPILER_VERSION):
        return {}
    entries = data.get("entries")
    return entries if isinstance(entries, dict) else {}


def _save_manifest(cache_dir, entries):
    # Drop entries whose source file no longer exists: they can never hit.
    # (Entries belonging to other entry files sharing this directory are
    # kept -- pruning is by file existence, not by "seen in this build".)
    entries = {p: e for p, e in entries.items() if os.path.isfile(p)}
    os.makedirs(cache_dir, exist_ok=True)
    tmp = os.path.join(cache_dir, _MANIFEST_NAME + ".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump({"format": CACHE_FORMAT, "version": COMPILER_VERSION,
                   "entries": entries}, f)
    os.replace(tmp, os.path.join(cache_dir, _MANIFEST_NAME))


def wipe_cache(cache_dir):
    """Remove the compilation cache directory. Returns True if removed."""
    if os.path.isdir(cache_dir):
        shutil.rmtree(cache_dir)
        return True
    return False


def _assemble_chunks(chunks, main_def, filename, annotate,
                     needs_asyncio_import=False):
    """Reproduce _generate_all's exact output from per-module chunks.

    A shared CodeGenerator separates consecutive top-level statements with
    one blank line and emits HEADER with no blank after it; emitting each
    module with a fresh generator and joining the non-empty chunks with
    "\\n\\n" after HEADER reproduces that byte-for-byte.
    """
    parts = [c for c in chunks if c.strip()]
    code = HEADER
    if needs_asyncio_import:
        code += "\nimport asyncio"
    if parts:
        code += "\n" + "\n\n".join(parts)
    code += "\n"
    if main_def is not None:
        code += "\nif __name__ == \"__main__\":\n"
        # v0.4.0: an async main runs on the event loop.
        call = ("asyncio.run(main())"
                if getattr(main_def, "is_async", False) else "main()")
        line = "    " + call
        if annotate and getattr(main_def, "line", 0):
            line += "  # AGK %s:%d" % (filename, main_def.line)
        code += line + "\n"
    return code


def compile_program_cached(program, filename="<string>", search_paths=(),
                           extra_top_levels=(), annotate=False,
                           cache_dir=None, entry_source=None, optimize=True):
    """Like compile_program, but reuses per-module results from the
    `.agkcache` manifest when fingerprints match.

    Returns (code, warnings, modules, status) where status is a list of
    (display_name, cache_hit) in build order: modules first (dependency
    order), then the entry file.

    entry_source: the entry file's source text, used for its fingerprint;
    read from filename when None. cache_dir=None disables caching and
    behaves exactly like compile_program.

    The cache key covers the compiler version, each module's source hash,
    the transitive dependency fingerprints, and the annotate flag.
    Callers that vary search_paths resolution or extra_top_levels between
    builds should use separate cache directories.
    """
    if cache_dir is None:
        code, warnings, modules = compile_program(
            program, filename=filename, search_paths=search_paths,
            extra_top_levels=extra_top_levels, annotate=annotate,
            optimize=optimize)
        return code, warnings, modules, []
    if search_paths is None:
        search_paths = [os.getcwd()]
    search_paths = list(search_paths)
    if filename not in (None, "<string>", "<input>", "<repl>"):
        entry_dir = os.path.dirname(os.path.abspath(filename))
    else:
        entry_dir = os.getcwd()
    pkg_dirs = package_module_dirs(entry_dir)
    modules = _resolve_modules(program, filename, search_paths,
                               pkg_dirs=pkg_dirs)
    resolved = {name for name, _, _ in modules}
    manifest = _load_manifest(cache_dir)

    src_hashes = {}
    dep_paths = {}
    for _name, mod_prog, mod_path in modules:
        apath = os.path.abspath(mod_path)
        with open(apath, "rb") as f:
            src_hashes[apath] = _source_hash_bytes(f.read())
        dep_paths[apath] = _direct_agk_deps(mod_prog, mod_path, search_paths,
                                            pkg_dirs)

    # Recursive fingerprints; a back edge in an import cycle contributes
    # the target's source-only hash so cycles terminate. A change anywhere
    # in the cycle still propagates: the back edge's target hash changes,
    # which changes every fingerprint around the cycle.
    # `salt` pins codegen-affecting options (currently annotate, optimize)
    # so builds with different options never share cache entries.
    salt = ("annotate" if annotate else "") + (";noopt" if not optimize else "")
    fps = {}
    visiting = set()

    def fingerprint(apath):
        if apath in fps:
            return fps[apath]
        if apath in visiting:
            return _fingerprint(src_hashes[apath], [], salt)
        visiting.add(apath)
        try:
            dfps = sorted(fingerprint(d) for d in dep_paths[apath])
            result = _fingerprint(src_hashes[apath], dfps, salt)
        finally:
            visiting.discard(apath)
        fps[apath] = result
        return result

    for apath in src_hashes:
        fingerprint(apath)

    def gen_chunk(prog, agk_file):
        cg = CodeGenerator()
        cg.generate_program(prog, skip_imports=resolved,
                            agk_file=agk_file if annotate else None)
        return "\n".join(cg.lines)

    warnings = []
    seen_progs = []
    chunks = []
    status = []
    for name, mod_prog, mod_path in modules:
        apath = os.path.abspath(mod_path)
        entry = manifest.get(apath)
        if (isinstance(entry, dict)
                and entry.get("fingerprint") == fps[apath]
                and isinstance(entry.get("chunk"), str)):
            chunks.append(entry["chunk"])
            warnings.extend(entry.get("warnings", []))
            status.append((name, True))
        else:
            _, mod_warnings = analyze(mod_prog, filename=mod_path,
                                      extra_top_levels=seen_progs)
            typecheck(mod_prog, filename=mod_path,
                      extra_top_levels=seen_progs)
            if optimize:
                optimize_program(mod_prog)
            warnings.extend(mod_warnings)
            chunk = gen_chunk(mod_prog, mod_path)
            chunks.append(chunk)
            status.append((name, False))
            manifest[apath] = {"fingerprint": fps[apath], "chunk": chunk,
                               "warnings": list(mod_warnings)}
        # analyze() only reads top-level names from these; the parsed ASTs
        # are deterministic from source, so later modules see identical
        # inputs whether or not this module was a cache hit.
        seen_progs.append(mod_prog)

    # The entry file: its fingerprint covers every module, so a hit here
    # implies all modules hit too; reuse the fully assembled output.
    entry_key = os.path.abspath(filename)
    if entry_source is None:
        with open(entry_key, "rb") as f:
            entry_source = f.read().decode("utf-8")
    entry_fp = _fingerprint(_source_hash_bytes(entry_source.encode("utf-8")),
                            sorted(fps.values()), salt)
    entry = manifest.get(entry_key)
    if (isinstance(entry, dict) and entry.get("fingerprint") == entry_fp
            and isinstance(entry.get("code"), str)):
        status.append((os.path.basename(filename), True))
        _save_manifest(cache_dir, manifest)
        return entry["code"], list(entry.get("warnings", [])), modules, status

    extra = list(extra_top_levels) + [mp for _, mp, _ in modules]
    program, main_warnings = analyze(program, filename=filename,
                                     extra_top_levels=extra)
    typecheck(program, filename=filename, extra_top_levels=extra)
    if optimize:
        optimize_program(program)
    warnings.extend(main_warnings)
    chunks.append(gen_chunk(program, filename))
    main_def = next((s for s in program.statements
                     if isinstance(s, A.FunctionDef) and s.name == "main"),
                    None)
    # v0.4.0: mirror _generate_all's asyncio handling for async programs.
    mod_progs = [mp for _, mp, _ in modules]
    uses_async = (program_uses_async(program)
                  or any(program_uses_async(mp) for mp in mod_progs))
    needs_asyncio_import = (uses_async
                            and not _asyncio_imported([program] + mod_progs))
    code = _assemble_chunks(chunks, main_def, filename, annotate,
                            needs_asyncio_import)
    status.append((os.path.basename(filename), False))
    manifest[entry_key] = {"fingerprint": entry_fp, "code": code,
                           "warnings": list(warnings)}
    _save_manifest(cache_dir, manifest)
    return code, warnings, modules, status


def compile_source_cached(source, filename="<string>", search_paths=(),
                          extra_top_levels=(), annotate=False,
                          cache_dir=None, optimize=True):
    """Compile AGK source to Python using the incremental cache.

    Returns (python_code, warnings, status); see compile_program_cached.
    """
    program = parse(source, filename=filename)
    code, warnings, _modules, status = compile_program_cached(
        program, filename=filename, search_paths=search_paths,
        extra_top_levels=extra_top_levels, annotate=annotate,
        cache_dir=cache_dir, entry_source=source, optimize=optimize)
    return code, warnings, status
